# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- $registry := .Values.global.registry -}}
{{- if .Values.image.registry -}}
{{- $registry = .Values.image.registry -}}
{{- end -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appOrch.fullname" . }}
  labels:
    app.kubernetes.io/part-of: orch-ui
    app: app-orch
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: orch-ui
      app: app-orch
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: orch-ui
        app: app-orch
        release: {{ .Release.Name }}
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx_configmap.yaml") . | sha256sum }}
        checksum/runtime-config: {{ include (print $.Template.BasePath "/runtime_config.yaml") . | sha256sum }}
    spec:
      {{- with $registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app-orch
          image: "{{- if hasKey $registry "name" }}{{ $registry.name }}/{{- end -}}{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: runtime-config
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "appOrch.fullname" . }}-nginx-config
            items:
              - key: config
                path: default.conf
        - name: runtime-config
          configMap:
            name: {{ include "appOrch.fullname" . }}-runtime-config
            items:
              - key: config
                path: runtime-config.js

