# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin.fullname" . }}-nginx-config
  labels:
    app.kubernetes.io/part-of: orch-ui
    release: {{ .Release.Name }}
data:
  config: |
{{ include "mfe.nginx-admin-config" .Values.nginx | indent 4 }}
