// Code generated by protoc-gen-go-const. DO NOT EDIT.

// source: schedule/v1/schedule.proto

package schedulev1

const (
	// Fields and Edges constants for "SingleScheduleResource"
	SingleScheduleResourceFieldResourceId     = "resource_id"
	SingleScheduleResourceFieldScheduleStatus = "schedule_status"
	SingleScheduleResourceFieldName           = "name"
	SingleScheduleResourceEdgeTargetSite      = "target_site"
	SingleScheduleResourceEdgeTargetHost      = "target_host"
	SingleScheduleResourceEdgeTargetWorkload  = "target_workload"
	SingleScheduleResourceEdgeTargetRegion    = "target_region"
	SingleScheduleResourceFieldStartSeconds   = "start_seconds"
	SingleScheduleResourceFieldEndSeconds     = "end_seconds"
	SingleScheduleResourceFieldTenantId       = "tenant_id"
	SingleScheduleResourceFieldCreatedAt      = "created_at"
	SingleScheduleResourceFieldUpdatedAt      = "updated_at"

	// Fields and Edges constants for "RepeatedScheduleResource"
	RepeatedScheduleResourceFieldResourceId      = "resource_id"
	RepeatedScheduleResourceFieldScheduleStatus  = "schedule_status"
	RepeatedScheduleResourceFieldName            = "name"
	RepeatedScheduleResourceEdgeTargetSite       = "target_site"
	RepeatedScheduleResourceEdgeTargetHost       = "target_host"
	RepeatedScheduleResourceEdgeTargetWorkload   = "target_workload"
	RepeatedScheduleResourceEdgeTargetRegion     = "target_region"
	RepeatedScheduleResourceFieldDurationSeconds = "duration_seconds"
	RepeatedScheduleResourceFieldCronMinutes     = "cron_minutes"
	RepeatedScheduleResourceFieldCronHours       = "cron_hours"
	RepeatedScheduleResourceFieldCronDayMonth    = "cron_day_month"
	RepeatedScheduleResourceFieldCronMonth       = "cron_month"
	RepeatedScheduleResourceFieldCronDayWeek     = "cron_day_week"
	RepeatedScheduleResourceFieldTenantId        = "tenant_id"
	RepeatedScheduleResourceFieldCreatedAt       = "created_at"
	RepeatedScheduleResourceFieldUpdatedAt       = "updated_at"
)
