# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: orch-ui-infra
description: Deploy the Edge-Native Software Platform Infrastructure pod
type: application
version: 1.0.8-dev
# Default appVersion will be overwritten by a the build to use the version from package.json.

appVersion: "1.0.8-dev"
dependencies: []
annotations: {}
