# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: location/v1/location.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ou import v1
from .provider import v1


@dataclass
class RegionResource(betterproto.Message):
    resource_id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    region_kind: str = betterproto.string_field(3)
    parent_region: "RegionResource" = betterproto.message_field(4)
    children: List["RegionResource"] = betterproto.message_field(5)
    metadata: str = betterproto.string_field(50)
    tenant_id: str = betterproto.string_field(100)
    created_at: str = betterproto.string_field(200)
    updated_at: str = betterproto.string_field(201)


@dataclass
class SiteResource(betterproto.Message):
    resource_id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    region: "RegionResource" = betterproto.message_field(4)
    ou: v1.OuResource = betterproto.message_field(5)
    address: str = betterproto.string_field(7)
    site_lat: int = betterproto.int32_field(8)
    site_lng: int = betterproto.int32_field(9)
    dns_servers: List[str] = betterproto.string_field(10)
    docker_registries: List[str] = betterproto.string_field(12)
    metrics_endpoint: str = betterproto.string_field(13)
    http_proxy: str = betterproto.string_field(16)
    https_proxy: str = betterproto.string_field(17)
    ftp_proxy: str = betterproto.string_field(18)
    no_proxy: str = betterproto.string_field(19)
    provider: v1.ProviderResource = betterproto.message_field(30)
    metadata: str = betterproto.string_field(50)
    tenant_id: str = betterproto.string_field(100)
    created_at: str = betterproto.string_field(200)
    updated_at: str = betterproto.string_field(201)
