// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hostresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/hoststorageresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
)

// HoststorageResourceQuery is the builder for querying HoststorageResource entities.
type HoststorageResourceQuery struct {
	config
	ctx        *QueryContext
	order      []hoststorageresource.OrderOption
	inters     []Interceptor
	predicates []predicate.HoststorageResource
	withHost   *HostResourceQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HoststorageResourceQuery builder.
func (hrq *HoststorageResourceQuery) Where(ps ...predicate.HoststorageResource) *HoststorageResourceQuery {
	hrq.predicates = append(hrq.predicates, ps...)
	return hrq
}

// Limit the number of records to be returned by this query.
func (hrq *HoststorageResourceQuery) Limit(limit int) *HoststorageResourceQuery {
	hrq.ctx.Limit = &limit
	return hrq
}

// Offset to start from.
func (hrq *HoststorageResourceQuery) Offset(offset int) *HoststorageResourceQuery {
	hrq.ctx.Offset = &offset
	return hrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hrq *HoststorageResourceQuery) Unique(unique bool) *HoststorageResourceQuery {
	hrq.ctx.Unique = &unique
	return hrq
}

// Order specifies how the records should be ordered.
func (hrq *HoststorageResourceQuery) Order(o ...hoststorageresource.OrderOption) *HoststorageResourceQuery {
	hrq.order = append(hrq.order, o...)
	return hrq
}

// QueryHost chains the current query on the "host" edge.
func (hrq *HoststorageResourceQuery) QueryHost() *HostResourceQuery {
	query := (&HostResourceClient{config: hrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hoststorageresource.Table, hoststorageresource.FieldID, selector),
			sqlgraph.To(hostresource.Table, hostresource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, hoststorageresource.HostTable, hoststorageresource.HostColumn),
		)
		fromU = sqlgraph.SetNeighbors(hrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HoststorageResource entity from the query.
// Returns a *NotFoundError when no HoststorageResource was found.
func (hrq *HoststorageResourceQuery) First(ctx context.Context) (*HoststorageResource, error) {
	nodes, err := hrq.Limit(1).All(setContextOp(ctx, hrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hoststorageresource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) FirstX(ctx context.Context) *HoststorageResource {
	node, err := hrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HoststorageResource ID from the query.
// Returns a *NotFoundError when no HoststorageResource ID was found.
func (hrq *HoststorageResourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hrq.Limit(1).IDs(setContextOp(ctx, hrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hoststorageresource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) FirstIDX(ctx context.Context) int {
	id, err := hrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HoststorageResource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HoststorageResource entity is found.
// Returns a *NotFoundError when no HoststorageResource entities are found.
func (hrq *HoststorageResourceQuery) Only(ctx context.Context) (*HoststorageResource, error) {
	nodes, err := hrq.Limit(2).All(setContextOp(ctx, hrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hoststorageresource.Label}
	default:
		return nil, &NotSingularError{hoststorageresource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) OnlyX(ctx context.Context) *HoststorageResource {
	node, err := hrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HoststorageResource ID in the query.
// Returns a *NotSingularError when more than one HoststorageResource ID is found.
// Returns a *NotFoundError when no entities are found.
func (hrq *HoststorageResourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hrq.Limit(2).IDs(setContextOp(ctx, hrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hoststorageresource.Label}
	default:
		err = &NotSingularError{hoststorageresource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := hrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HoststorageResources.
func (hrq *HoststorageResourceQuery) All(ctx context.Context) ([]*HoststorageResource, error) {
	ctx = setContextOp(ctx, hrq.ctx, ent.OpQueryAll)
	if err := hrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HoststorageResource, *HoststorageResourceQuery]()
	return withInterceptors[[]*HoststorageResource](ctx, hrq, qr, hrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) AllX(ctx context.Context) []*HoststorageResource {
	nodes, err := hrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HoststorageResource IDs.
func (hrq *HoststorageResourceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hrq.ctx.Unique == nil && hrq.path != nil {
		hrq.Unique(true)
	}
	ctx = setContextOp(ctx, hrq.ctx, ent.OpQueryIDs)
	if err = hrq.Select(hoststorageresource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) IDsX(ctx context.Context) []int {
	ids, err := hrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hrq *HoststorageResourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hrq.ctx, ent.OpQueryCount)
	if err := hrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hrq, querierCount[*HoststorageResourceQuery](), hrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) CountX(ctx context.Context) int {
	count, err := hrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hrq *HoststorageResourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hrq.ctx, ent.OpQueryExist)
	switch _, err := hrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hrq *HoststorageResourceQuery) ExistX(ctx context.Context) bool {
	exist, err := hrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HoststorageResourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hrq *HoststorageResourceQuery) Clone() *HoststorageResourceQuery {
	if hrq == nil {
		return nil
	}
	return &HoststorageResourceQuery{
		config:     hrq.config,
		ctx:        hrq.ctx.Clone(),
		order:      append([]hoststorageresource.OrderOption{}, hrq.order...),
		inters:     append([]Interceptor{}, hrq.inters...),
		predicates: append([]predicate.HoststorageResource{}, hrq.predicates...),
		withHost:   hrq.withHost.Clone(),
		// clone intermediate query.
		sql:  hrq.sql.Clone(),
		path: hrq.path,
	}
}

// WithHost tells the query-builder to eager-load the nodes that are connected to
// the "host" edge. The optional arguments are used to configure the query builder of the edge.
func (hrq *HoststorageResourceQuery) WithHost(opts ...func(*HostResourceQuery)) *HoststorageResourceQuery {
	query := (&HostResourceClient{config: hrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hrq.withHost = query
	return hrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HoststorageResource.Query().
//		GroupBy(hoststorageresource.FieldResourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hrq *HoststorageResourceQuery) GroupBy(field string, fields ...string) *HoststorageResourceGroupBy {
	hrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HoststorageResourceGroupBy{build: hrq}
	grbuild.flds = &hrq.ctx.Fields
	grbuild.label = hoststorageresource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//	}
//
//	client.HoststorageResource.Query().
//		Select(hoststorageresource.FieldResourceID).
//		Scan(ctx, &v)
func (hrq *HoststorageResourceQuery) Select(fields ...string) *HoststorageResourceSelect {
	hrq.ctx.Fields = append(hrq.ctx.Fields, fields...)
	sbuild := &HoststorageResourceSelect{HoststorageResourceQuery: hrq}
	sbuild.label = hoststorageresource.Label
	sbuild.flds, sbuild.scan = &hrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HoststorageResourceSelect configured with the given aggregations.
func (hrq *HoststorageResourceQuery) Aggregate(fns ...AggregateFunc) *HoststorageResourceSelect {
	return hrq.Select().Aggregate(fns...)
}

func (hrq *HoststorageResourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hrq); err != nil {
				return err
			}
		}
	}
	for _, f := range hrq.ctx.Fields {
		if !hoststorageresource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hrq.path != nil {
		prev, err := hrq.path(ctx)
		if err != nil {
			return err
		}
		hrq.sql = prev
	}
	return nil
}

func (hrq *HoststorageResourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HoststorageResource, error) {
	var (
		nodes       = []*HoststorageResource{}
		withFKs     = hrq.withFKs
		_spec       = hrq.querySpec()
		loadedTypes = [1]bool{
			hrq.withHost != nil,
		}
	)
	if hrq.withHost != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, hoststorageresource.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HoststorageResource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HoststorageResource{config: hrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hrq.withHost; query != nil {
		if err := hrq.loadHost(ctx, query, nodes, nil,
			func(n *HoststorageResource, e *HostResource) { n.Edges.Host = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hrq *HoststorageResourceQuery) loadHost(ctx context.Context, query *HostResourceQuery, nodes []*HoststorageResource, init func(*HoststorageResource), assign func(*HoststorageResource, *HostResource)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HoststorageResource)
	for i := range nodes {
		if nodes[i].hoststorage_resource_host == nil {
			continue
		}
		fk := *nodes[i].hoststorage_resource_host
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hostresource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "hoststorage_resource_host" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (hrq *HoststorageResourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hrq.querySpec()
	_spec.Node.Columns = hrq.ctx.Fields
	if len(hrq.ctx.Fields) > 0 {
		_spec.Unique = hrq.ctx.Unique != nil && *hrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hrq.driver, _spec)
}

func (hrq *HoststorageResourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hoststorageresource.Table, hoststorageresource.Columns, sqlgraph.NewFieldSpec(hoststorageresource.FieldID, field.TypeInt))
	_spec.From = hrq.sql
	if unique := hrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hrq.path != nil {
		_spec.Unique = true
	}
	if fields := hrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hoststorageresource.FieldID)
		for i := range fields {
			if fields[i] != hoststorageresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hrq *HoststorageResourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hrq.driver.Dialect())
	t1 := builder.Table(hoststorageresource.Table)
	columns := hrq.ctx.Fields
	if len(columns) == 0 {
		columns = hoststorageresource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hrq.sql != nil {
		selector = hrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hrq.ctx.Unique != nil && *hrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hrq.predicates {
		p(selector)
	}
	for _, p := range hrq.order {
		p(selector)
	}
	if offset := hrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HoststorageResourceGroupBy is the group-by builder for HoststorageResource entities.
type HoststorageResourceGroupBy struct {
	selector
	build *HoststorageResourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hrgb *HoststorageResourceGroupBy) Aggregate(fns ...AggregateFunc) *HoststorageResourceGroupBy {
	hrgb.fns = append(hrgb.fns, fns...)
	return hrgb
}

// Scan applies the selector query and scans the result into the given value.
func (hrgb *HoststorageResourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hrgb.build.ctx, ent.OpQueryGroupBy)
	if err := hrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HoststorageResourceQuery, *HoststorageResourceGroupBy](ctx, hrgb.build, hrgb, hrgb.build.inters, v)
}

func (hrgb *HoststorageResourceGroupBy) sqlScan(ctx context.Context, root *HoststorageResourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hrgb.fns))
	for _, fn := range hrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hrgb.flds)+len(hrgb.fns))
		for _, f := range *hrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HoststorageResourceSelect is the builder for selecting fields of HoststorageResource entities.
type HoststorageResourceSelect struct {
	*HoststorageResourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hrs *HoststorageResourceSelect) Aggregate(fns ...AggregateFunc) *HoststorageResourceSelect {
	hrs.fns = append(hrs.fns, fns...)
	return hrs
}

// Scan applies the selector query and scans the result into the given value.
func (hrs *HoststorageResourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hrs.ctx, ent.OpQuerySelect)
	if err := hrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HoststorageResourceQuery, *HoststorageResourceSelect](ctx, hrs.HoststorageResourceQuery, hrs, hrs.inters, v)
}

func (hrs *HoststorageResourceSelect) sqlScan(ctx context.Context, root *HoststorageResourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hrs.fns))
	for _, fn := range hrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
