// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/instanceresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
)

// InstanceResourceDelete is the builder for deleting a InstanceResource entity.
type InstanceResourceDelete struct {
	config
	hooks    []Hook
	mutation *InstanceResourceMutation
}

// Where appends a list predicates to the InstanceResourceDelete builder.
func (ird *InstanceResourceDelete) Where(ps ...predicate.InstanceResource) *InstanceResourceDelete {
	ird.mutation.Where(ps...)
	return ird
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ird *InstanceResourceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ird.sqlExec, ird.mutation, ird.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ird *InstanceResourceDelete) ExecX(ctx context.Context) int {
	n, err := ird.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ird *InstanceResourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(instanceresource.Table, sqlgraph.NewFieldSpec(instanceresource.FieldID, field.TypeInt))
	if ps := ird.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ird.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ird.mutation.done = true
	return affected, err
}

// InstanceResourceDeleteOne is the builder for deleting a single InstanceResource entity.
type InstanceResourceDeleteOne struct {
	ird *InstanceResourceDelete
}

// Where appends a list predicates to the InstanceResourceDelete builder.
func (irdo *InstanceResourceDeleteOne) Where(ps ...predicate.InstanceResource) *InstanceResourceDeleteOne {
	irdo.ird.mutation.Where(ps...)
	return irdo
}

// Exec executes the deletion query.
func (irdo *InstanceResourceDeleteOne) Exec(ctx context.Context) error {
	n, err := irdo.ird.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{instanceresource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (irdo *InstanceResourceDeleteOne) ExecX(ctx context.Context) {
	if err := irdo.Exec(ctx); err != nil {
		panic(err)
	}
}
