// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/operatingsystemresource"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
)

// OperatingSystemResourceQuery is the builder for querying OperatingSystemResource entities.
type OperatingSystemResourceQuery struct {
	config
	ctx        *QueryContext
	order      []operatingsystemresource.OrderOption
	inters     []Interceptor
	predicates []predicate.OperatingSystemResource
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OperatingSystemResourceQuery builder.
func (osrq *OperatingSystemResourceQuery) Where(ps ...predicate.OperatingSystemResource) *OperatingSystemResourceQuery {
	osrq.predicates = append(osrq.predicates, ps...)
	return osrq
}

// Limit the number of records to be returned by this query.
func (osrq *OperatingSystemResourceQuery) Limit(limit int) *OperatingSystemResourceQuery {
	osrq.ctx.Limit = &limit
	return osrq
}

// Offset to start from.
func (osrq *OperatingSystemResourceQuery) Offset(offset int) *OperatingSystemResourceQuery {
	osrq.ctx.Offset = &offset
	return osrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (osrq *OperatingSystemResourceQuery) Unique(unique bool) *OperatingSystemResourceQuery {
	osrq.ctx.Unique = &unique
	return osrq
}

// Order specifies how the records should be ordered.
func (osrq *OperatingSystemResourceQuery) Order(o ...operatingsystemresource.OrderOption) *OperatingSystemResourceQuery {
	osrq.order = append(osrq.order, o...)
	return osrq
}

// First returns the first OperatingSystemResource entity from the query.
// Returns a *NotFoundError when no OperatingSystemResource was found.
func (osrq *OperatingSystemResourceQuery) First(ctx context.Context) (*OperatingSystemResource, error) {
	nodes, err := osrq.Limit(1).All(setContextOp(ctx, osrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{operatingsystemresource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) FirstX(ctx context.Context) *OperatingSystemResource {
	node, err := osrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OperatingSystemResource ID from the query.
// Returns a *NotFoundError when no OperatingSystemResource ID was found.
func (osrq *OperatingSystemResourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = osrq.Limit(1).IDs(setContextOp(ctx, osrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{operatingsystemresource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) FirstIDX(ctx context.Context) int {
	id, err := osrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OperatingSystemResource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OperatingSystemResource entity is found.
// Returns a *NotFoundError when no OperatingSystemResource entities are found.
func (osrq *OperatingSystemResourceQuery) Only(ctx context.Context) (*OperatingSystemResource, error) {
	nodes, err := osrq.Limit(2).All(setContextOp(ctx, osrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{operatingsystemresource.Label}
	default:
		return nil, &NotSingularError{operatingsystemresource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) OnlyX(ctx context.Context) *OperatingSystemResource {
	node, err := osrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OperatingSystemResource ID in the query.
// Returns a *NotSingularError when more than one OperatingSystemResource ID is found.
// Returns a *NotFoundError when no entities are found.
func (osrq *OperatingSystemResourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = osrq.Limit(2).IDs(setContextOp(ctx, osrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{operatingsystemresource.Label}
	default:
		err = &NotSingularError{operatingsystemresource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := osrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OperatingSystemResources.
func (osrq *OperatingSystemResourceQuery) All(ctx context.Context) ([]*OperatingSystemResource, error) {
	ctx = setContextOp(ctx, osrq.ctx, ent.OpQueryAll)
	if err := osrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OperatingSystemResource, *OperatingSystemResourceQuery]()
	return withInterceptors[[]*OperatingSystemResource](ctx, osrq, qr, osrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) AllX(ctx context.Context) []*OperatingSystemResource {
	nodes, err := osrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OperatingSystemResource IDs.
func (osrq *OperatingSystemResourceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if osrq.ctx.Unique == nil && osrq.path != nil {
		osrq.Unique(true)
	}
	ctx = setContextOp(ctx, osrq.ctx, ent.OpQueryIDs)
	if err = osrq.Select(operatingsystemresource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) IDsX(ctx context.Context) []int {
	ids, err := osrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (osrq *OperatingSystemResourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, osrq.ctx, ent.OpQueryCount)
	if err := osrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, osrq, querierCount[*OperatingSystemResourceQuery](), osrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) CountX(ctx context.Context) int {
	count, err := osrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (osrq *OperatingSystemResourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, osrq.ctx, ent.OpQueryExist)
	switch _, err := osrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (osrq *OperatingSystemResourceQuery) ExistX(ctx context.Context) bool {
	exist, err := osrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OperatingSystemResourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (osrq *OperatingSystemResourceQuery) Clone() *OperatingSystemResourceQuery {
	if osrq == nil {
		return nil
	}
	return &OperatingSystemResourceQuery{
		config:     osrq.config,
		ctx:        osrq.ctx.Clone(),
		order:      append([]operatingsystemresource.OrderOption{}, osrq.order...),
		inters:     append([]Interceptor{}, osrq.inters...),
		predicates: append([]predicate.OperatingSystemResource{}, osrq.predicates...),
		// clone intermediate query.
		sql:  osrq.sql.Clone(),
		path: osrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OperatingSystemResource.Query().
//		GroupBy(operatingsystemresource.FieldResourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (osrq *OperatingSystemResourceQuery) GroupBy(field string, fields ...string) *OperatingSystemResourceGroupBy {
	osrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OperatingSystemResourceGroupBy{build: osrq}
	grbuild.flds = &osrq.ctx.Fields
	grbuild.label = operatingsystemresource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//	}
//
//	client.OperatingSystemResource.Query().
//		Select(operatingsystemresource.FieldResourceID).
//		Scan(ctx, &v)
func (osrq *OperatingSystemResourceQuery) Select(fields ...string) *OperatingSystemResourceSelect {
	osrq.ctx.Fields = append(osrq.ctx.Fields, fields...)
	sbuild := &OperatingSystemResourceSelect{OperatingSystemResourceQuery: osrq}
	sbuild.label = operatingsystemresource.Label
	sbuild.flds, sbuild.scan = &osrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OperatingSystemResourceSelect configured with the given aggregations.
func (osrq *OperatingSystemResourceQuery) Aggregate(fns ...AggregateFunc) *OperatingSystemResourceSelect {
	return osrq.Select().Aggregate(fns...)
}

func (osrq *OperatingSystemResourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range osrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, osrq); err != nil {
				return err
			}
		}
	}
	for _, f := range osrq.ctx.Fields {
		if !operatingsystemresource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if osrq.path != nil {
		prev, err := osrq.path(ctx)
		if err != nil {
			return err
		}
		osrq.sql = prev
	}
	return nil
}

func (osrq *OperatingSystemResourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OperatingSystemResource, error) {
	var (
		nodes = []*OperatingSystemResource{}
		_spec = osrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OperatingSystemResource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OperatingSystemResource{config: osrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, osrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (osrq *OperatingSystemResourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := osrq.querySpec()
	_spec.Node.Columns = osrq.ctx.Fields
	if len(osrq.ctx.Fields) > 0 {
		_spec.Unique = osrq.ctx.Unique != nil && *osrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, osrq.driver, _spec)
}

func (osrq *OperatingSystemResourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(operatingsystemresource.Table, operatingsystemresource.Columns, sqlgraph.NewFieldSpec(operatingsystemresource.FieldID, field.TypeInt))
	_spec.From = osrq.sql
	if unique := osrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if osrq.path != nil {
		_spec.Unique = true
	}
	if fields := osrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operatingsystemresource.FieldID)
		for i := range fields {
			if fields[i] != operatingsystemresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := osrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := osrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := osrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := osrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (osrq *OperatingSystemResourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(osrq.driver.Dialect())
	t1 := builder.Table(operatingsystemresource.Table)
	columns := osrq.ctx.Fields
	if len(columns) == 0 {
		columns = operatingsystemresource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if osrq.sql != nil {
		selector = osrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if osrq.ctx.Unique != nil && *osrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range osrq.predicates {
		p(selector)
	}
	for _, p := range osrq.order {
		p(selector)
	}
	if offset := osrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := osrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OperatingSystemResourceGroupBy is the group-by builder for OperatingSystemResource entities.
type OperatingSystemResourceGroupBy struct {
	selector
	build *OperatingSystemResourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (osrgb *OperatingSystemResourceGroupBy) Aggregate(fns ...AggregateFunc) *OperatingSystemResourceGroupBy {
	osrgb.fns = append(osrgb.fns, fns...)
	return osrgb
}

// Scan applies the selector query and scans the result into the given value.
func (osrgb *OperatingSystemResourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, osrgb.build.ctx, ent.OpQueryGroupBy)
	if err := osrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OperatingSystemResourceQuery, *OperatingSystemResourceGroupBy](ctx, osrgb.build, osrgb, osrgb.build.inters, v)
}

func (osrgb *OperatingSystemResourceGroupBy) sqlScan(ctx context.Context, root *OperatingSystemResourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(osrgb.fns))
	for _, fn := range osrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*osrgb.flds)+len(osrgb.fns))
		for _, f := range *osrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*osrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := osrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OperatingSystemResourceSelect is the builder for selecting fields of OperatingSystemResource entities.
type OperatingSystemResourceSelect struct {
	*OperatingSystemResourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (osrs *OperatingSystemResourceSelect) Aggregate(fns ...AggregateFunc) *OperatingSystemResourceSelect {
	osrs.fns = append(osrs.fns, fns...)
	return osrs
}

// Scan applies the selector query and scans the result into the given value.
func (osrs *OperatingSystemResourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, osrs.ctx, ent.OpQuerySelect)
	if err := osrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OperatingSystemResourceQuery, *OperatingSystemResourceSelect](ctx, osrs.OperatingSystemResourceQuery, osrs, osrs.inters, v)
}

func (osrs *OperatingSystemResourceSelect) sqlScan(ctx context.Context, root *OperatingSystemResourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(osrs.fns))
	for _, fn := range osrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*osrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := osrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
