# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
name: E2E Tests Workflow
on:
  workflow_call
env:
  CYPRESS_BASE_URL: "http://localhost:8080"

jobs:
  pre-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
    with:
      bootstrap_tools: "base"
      run_version_check: true
      run_lint: false # TODO fix lint and enable
      run_test: false
      run_build: true
      run_scan_containers: false
      prefix_tag_separator: "/"
      project_folder: tests
      orch_ci_repo_ref: main
    secrets: inherit
  # run-e2e-tests-pipeline:
  #   runs-on: 'ubuntu-latest'
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4

  #     - name: Cache npm dependencies
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18.17.1
  #         cache: "npm"

  #     - name: Install dependencies
  #       run: |
  #         node -v
  #         npm -v
  #         npm ci

  #     - name: Build the test code
  #       run: npm run tests:build

      # - name: Build production UI with mock server
      #   run: bash tools/build-all-mock.sh

      # - name: Serve the UI
      #   run: npx serve dist -s --no-request-logging -p 8080 &

      # - name: Run EIM tests
      #   run: cd tests; npx cypress run --e2e -s cypress/e2e/infra/infra-smoke.cy.ts --env EN_UUID=398395da-c10e-7c47-9b4f-efb34c0b261e
