# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
name: Library Workflow
on:
  workflow_call

jobs:
  run-library-pipeline:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SYS_ORCH_GITHUB }}

      - name: Cache npm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: "npm"

      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci

      - name: Code style check
        run: npm run library:lint
      
      - name: Run api:generate script
        run: npm run api:generate

      - name: Check for Changes in library/apis
        shell: bash
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD library/apis/)
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "::error::API file changes detected in library/apis: $CHANGED_FILES"
            exit 1  # Fail the step
          else
            echo "No changes detected in the library/apis folder."
          fi
        continue-on-error: true

      - name: Cypress Component Tests
        run: npm run library:cy:component
