---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Exporters Inventory

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'exporters-inventory/**'
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_security_scans: true
      run_version_check: false
      run_dep_version_check: true
      run_build: false
      run_docker_build: false
      run_docker_push: false
      run_version_tag: true
      run_artifact: false
      prefix_tag_separator: "/"
      project_folder: "exporters-inventory"
    secrets: inherit
