---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge OS Profiles

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'os-profiles/**'

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      bootstrap_tools: "go,yq,aws,oras"
      run_security_scans: true
      run_version_check: true
      run_dep_version_check: false
      run_build: false
      run_docker_build: false
      run_docker_push: false
      run_artifact: true
      run_version_tag: true
      prefix_tag_separator: "/"
      project_folder: "os-profiles"
      persist_creds: true
    secrets: inherit
