---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Bulk Import Tools

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'bulk-import-tools/**'
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@test_ossf
    with:
      run_security_scans: true
      run_version_check: false
      run_dep_version_check: true
      run_build: true
      run_docker_build: false
      # TODO: add publish of binaries
      run_docker_push: false
      run_version_tag: true
      run_artifact: true
      prefix_tag_separator: "/"
      project_folder: "bulk-import-tools"
    secrets: inherit
